# Site Settings
title: Lukasz' Resume
url: 'http://www.lenart.org.pl'
baseurl: '' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: ≈Åukasz Lenart
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm an application developer in a wide variety of business applications, particularly experienced in client/server and relational database design using Java and Scala. My specialties include social insurance, automotive, production, purchasing, and banking. I'm a Lead Developer on the Apache Struts project since 2011. I hold a Bachelor of Computer Systems with an emphasis on Information Systems"

#sidebar links
email: lukasz@lenart.org.pl
phone: +48 606 323 122
website: lenart.org.pl #do not add http://
linkedin: lukaszlenart
github: lukaszlenart
twitter: '@lukaszlenart'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

exclude: [update.sh]
